version: '3'

services:
  spotify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 11030:3000
    environment:
      SESSION_SECRET: ''
      CLIENT_ID: ''
      CLIENT_SECRET: ''
      REDIRECT_URI: ''
    restart: always
    networks:
      spotifyNetwork:
        ipv4_address: 172.33.52.3

networks:
  spotifyNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.52.0/22
          gateway: 172.33.52.1
